# Generated by Django 5.2.1 on 2025-12-28 08:33

import applications.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Candidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("age", models.IntegerField(blank=True, null=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("gender", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "marital_status",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("community", models.CharField(blank=True, max_length=100, null=True)),
                ("caste", models.CharField(blank=True, max_length=100, null=True)),
                ("pan_number", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_primary",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone_secondary",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=applications.utils.candidate_profile_path,
                    ),
                ),
                ("address", models.TextField(blank=True, null=True)),
                ("total_experience_years", models.IntegerField(blank=True, null=True)),
                ("present_post_years", models.IntegerField(blank=True, null=True)),
                (
                    "mother_name_and_occupation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Document_Type",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LevelOfEducation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=150, null=True, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminLoginLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username_attempted", models.CharField(blank=True, max_length=150)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("LOGIN_SUCCESS", "Login Success"),
                            ("LOGIN_FAILED", "Login Failed"),
                            ("LOGOUT", "Logout"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("session_key", models.CharField(blank=True, max_length=40, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Login Log",
                "verbose_name_plural": "Admin Login Logs",
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="ApplicationUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("device_type", models.CharField(max_length=50)),
                (
                    "action",
                    models.CharField(
                        choices=[("FORM_SUBMITTED", "Form Submitted")], max_length=50
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_logs",
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AcademicExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                (
                    "relieving_date",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("years", models.IntegerField(blank=True, null=True)),
                ("months", models.IntegerField(blank=True, null=True)),
                ("days", models.IntegerField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contribution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "degree_code",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("degree", models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                "ordering": ["degree"],
                "indexes": [
                    models.Index(
                        fields=["degree_code"], name="application_degree__72a548_idx"
                    ),
                    models.Index(
                        fields=["degree"], name="application_degree_13dbae_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=150, null=True)),
                ("code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="departments",
                        to="applications.degree",
                    ),
                ),
            ],
            options={
                "ordering": ["degree", "name"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=applications.utils.candidate_document_path,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.document_type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Certificate_Permission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_permissions",
                        to="applications.department",
                    ),
                ),
                (
                    "document_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate_permissions",
                        to="applications.document_type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IndustryExperience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "nature_of_work",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("joining_date", models.DateField(blank=True, null=True)),
                ("relieving_date", models.DateField(blank=True, null=True)),
                ("years", models.IntegerField(blank=True, null=True)),
                ("months", models.IntegerField(blank=True, null=True)),
                ("days", models.IntegerField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "year_of_passing",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                (
                    "institution",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("university", models.CharField(blank=True, max_length=200, null=True)),
                ("percentage", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "class_obtained",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applications.degree",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applications.levelofeducation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PositionApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "present_designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "present_organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "assistant_professor_years",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "associate_professor_years",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "professor_years",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "other_years",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "research_experience_years",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "industry_experience_years",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "journal_publications",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "conference_publications",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "students_guided_completed",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "students_guided_ongoing",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "community_and_caste",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applications.department",
                    ),
                ),
                (
                    "position_applied",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applications.designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Programme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programme_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                ("count", models.IntegerField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProgrammesPublications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "programmes",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                (
                    "publications",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                (
                    "research_publications_details",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                ("research_scholars_details", models.TextField(blank=True, null=True)),
                (
                    "sponsored_projects",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                (
                    "memberships",
                    models.CharField(default="", max_length=1000, null=True),
                ),
                ("awards", models.CharField(default="", max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="programmes_publications",
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Publication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(blank=True, null=True)),
                ("indexing", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Qualification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "specialization",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("institute", models.CharField(blank=True, max_length=200, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
                (
                    "qualification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="applications.degree",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Referee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "organization",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "contact_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResearchDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mode_ug", models.CharField(blank=True, max_length=30, null=True)),
                ("mode_pg", models.CharField(blank=True, max_length=30, null=True)),
                ("mode_phd", models.CharField(blank=True, max_length=30, null=True)),
                ("arrears_ug", models.IntegerField(blank=True, null=True)),
                ("arrears_pg", models.IntegerField(blank=True, null=True)),
                ("gate_score", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "net_slet_score",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("me_thesis_title", models.TextField(blank=True, null=True)),
                ("phd_thesis_title", models.TextField(blank=True, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SponsoredProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=300, null=True)),
                ("duration", models.CharField(blank=True, max_length=50, null=True)),
                ("amount", models.PositiveIntegerField(blank=True, null=True)),
                ("agency", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TeachingSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "subject_and_result",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitorLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("device_type", models.CharField(max_length=50)),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdminPasswordOTP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("otp_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("is_used", models.BooleanField(default=False)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "is_used"],
                        name="application_user_id_da1df9_idx",
                    ),
                    models.Index(
                        fields=["expires_at"], name="application_expires_5ddfab_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["name"], name="application_name_7eff2e_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(fields=["code"], name="application_code_a1b958_idx"),
        ),
        migrations.AddIndex(
            model_name="department",
            index=models.Index(
                fields=["degree"], name="application_degree__264765_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["ip_address"], name="application_ip_addr_2599b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="visitorlog",
            index=models.Index(
                fields=["timestamp"], name="application_timesta_2dcdca_idx"
            ),
        ),
    ]
