# Generated by Django 5.2.5 on 2026-01-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="referee",
            name="contact_number",
        ),
        migrations.AddField(
            model_name="referee",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="referee",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
