# Generated by Django 5.2.5 on 2026-01-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="positionapplication",
            name="department",
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="departments",
            field=models.ManyToManyField(blank=True, to="applications.department"),
        ),
    ]
