# Generated by Django 5.2.5 on 2026-01-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_remove_referee_contact_number_referee_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmepublicationentry",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="programmepublicationentry",
            name="project_amount",
        ),
        migrations.RemoveField(
            model_name="programmepublicationentry",
            name="project_duration",
        ),
        migrations.RemoveField(
            model_name="programmepublicationentry",
            name="project_funding_agency",
        ),
        migrations.RemoveField(
            model_name="programmepublicationentry",
            name="project_status",
        ),
        migrations.RemoveField(
            model_name="programmepublicationentry",
            name="project_title",
        ),
        migrations.RemoveField(
            model_name="programmepublicationentry",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="programmepublicationentry",
            name="entry_type",
            field=models.CharField(
                choices=[
                    ("PROGRAMME", "Programme"),
                    ("PUBLICATION", "Publication"),
                    ("RESEARCH_PUB", "Research Publication (Scopus)"),
                    ("MEMBERSHIP", "Membership/Fellowship"),
                    ("AWARD", "Award/Recognition"),
                    ("RESEARCH_SCHOLARS", "Research Scholars Guided"),
                ],
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="ProfessionalActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("award", models.CharField(blank=True, max_length=255, null=True)),
                ("particular", models.CharField(blank=True, max_length=255, null=True)),
                ("agency", models.CharField(blank=True, max_length=255, null=True)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="professional_activities",
                        to="applications.candidate",
                    ),
                ),
            ],
            options={
                "ordering": ["-year", "-id"],
            },
        ),
    ]
