# Generated by Django 5.2.5 on 2026-01-08 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0002_remove_positionapplication_department_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="positionapplication",
            old_name="departments",
            new_name="department",
        ),
    ]
