# Generated by Django 5.2.5 on 2026-01-12 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_remove_programmepublicationentry_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professionalactivity",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="professionalactivity",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="sponsoredproject",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("completed", "Completed"), ("ongoing", "Ongoing")],
                default="completed",
                max_length=20,
                null=True,
            ),
        ),
    ]
