# Generated by Django 5.2.5 on 2026-01-08 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_rename_departments_positionapplication_department"),
    ]

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("code", models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="languages",
            field=models.ManyToManyField(
                blank=True, related_name="applications", to="applications.language"
            ),
        ),
    ]
