# Generated by Django 5.2.5 on 2026-01-09 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_language_positionapplication_languages"),
    ]

    operations = [
        migrations.CreateModel(
            name="Community",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("code", models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="positionapplication",
            name="community_and_caste",
        ),
        migrations.RemoveField(
            model_name="positionapplication",
            name="department",
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="departments",
            field=models.ManyToManyField(
                blank=True, related_name="applications", to="applications.department"
            ),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="applications.community",
            ),
        ),
    ]
