# Generated by Django 5.2.5 on 2026-01-13 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0004_remove_professionalactivity_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="caste",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="mother_name_and_occupation",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="present_post_years",
        ),
        migrations.RemoveField(
            model_name="candidate",
            name="total_experience_years",
        ),
        migrations.RemoveField(
            model_name="positionapplication",
            name="created_at",
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="present_post_years",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="total_experience_years",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
