# Generated by Django 5.2.5 on 2026-01-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0005_community_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="candidate",
            name="community",
        ),
    ]
