# Generated by Django 5.2.5 on 2026-01-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_remove_candidate_community"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sponsoredproject",
            name="amount",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
