# Generated by Django 5.2.5 on 2026-01-10 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_alter_sponsoredproject_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="positionapplication",
            name="community",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.RemoveField(
            model_name="positionapplication",
            name="languages",
        ),
        migrations.DeleteModel(
            name="Community",
        ),
        migrations.DeleteModel(
            name="Language",
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
