# Generated by Django 5.2.5 on 2026-01-10 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0008_alter_positionapplication_community_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="programmespublications",
            name="candidate",
        ),
        migrations.RemoveField(
            model_name="publication",
            name="candidate",
        ),
        migrations.CreateModel(
            name="ProgrammePublicationEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("PROGRAMME", "Programme"),
                            ("PUBLICATION", "Publication"),
                            ("RESEARCH_PUB", "Research Publication (Scopus)"),
                            ("SPONSORED_PROJECT", "Sponsored Project"),
                            ("MEMBERSHIP", "Membership/Fellowship"),
                            ("AWARD", "Award/Recognition"),
                            ("RESEARCH_SCHOLARS", "Research Scholars Guided"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "programme_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "programme_category",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("programme_count", models.IntegerField(blank=True, null=True)),
                ("publication_title", models.TextField(blank=True, null=True)),
                (
                    "publication_indexing",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("details", models.TextField(blank=True, null=True)),
                ("project_title", models.TextField(blank=True, null=True)),
                (
                    "project_status",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("project_funding_agency", models.TextField(blank=True, null=True)),
                ("project_amount", models.IntegerField(blank=True, null=True)),
                (
                    "project_duration",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pp_entries",
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Programme",
        ),
        migrations.DeleteModel(
            name="ProgrammesPublications",
        ),
        migrations.DeleteModel(
            name="Publication",
        ),
    ]
