# Generated by Django 5.2.5 on 2026-01-10 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_remove_programmespublications_candidate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teachingsubject",
            name="candidate",
        ),
        migrations.CreateModel(
            name="TeachingContributionEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(blank=True, max_length=10, null=True)),
                ("subject", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "pass_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("department_contribution", models.TextField(blank=True, null=True)),
                ("college_contribution", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teaching_entries",
                        to="applications.candidate",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Contribution",
        ),
        migrations.DeleteModel(
            name="TeachingSubject",
        ),
    ]
