# Generated by Django 5.2.5 on 2026-01-10 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_remove_teachingsubject_candidate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationCertificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=20)),
                (
                    "file",
                    models.FileField(upload_to="candidate/education_certificates/"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.candidate",
                    ),
                ),
            ],
            options={
                "unique_together": {("candidate", "level")},
            },
        ),
    ]
