# Generated by Django 5.2.5 on 2026-01-11 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0011_educationcertificate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchdetails",
            name="arrears_pg",
        ),
        migrations.RemoveField(
            model_name="researchdetails",
            name="arrears_ug",
        ),
        migrations.RemoveField(
            model_name="researchdetails",
            name="me_thesis_title",
        ),
    ]
