# Generated by Django 5.2.5 on 2026-01-11 02:49

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_remove_researchdetails_arrears_pg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="researchdetails",
            name="gate_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.models.research_cert_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="researchdetails",
            name="net_slet_certificate",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=applications.models.research_cert_upload_to,
            ),
        ),
    ]
