# Generated by Django 5.2.5 on 2026-01-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_researchdetails_gate_certificate_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="positionapplication",
            name="community",
        ),
        migrations.RemoveField(
            model_name="positionapplication",
            name="languages",
        ),
        migrations.AddField(
            model_name="candidate",
            name="community",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="candidate",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="arrears_pg",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name="positionapplication",
            name="arrears_ug",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
